services:
  dev-environment:
    image: dimensionalos/dev-base
    container_name: dimos-dev
    volumes:
      - ../../../:/app
    environment:
      - PYTHONPATH=/app
    ports:
      - "5555:5555"
      - "3000:3000"
    stdin_open: true
    tty: true
    command: /bin/bash
